// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Message struct {
	ID int64
	// receipent phone number
	RecipientPhone string
	// message content
	Content string
	Status  string
	// message ID from the messaging service
	Messageid sql.NullString
	// when the message was sent
	SentAt sql.NullTime
	// Record creation timestamp
	Createdon sql.NullTime
	// Record last updated timestamp
	Updatedon sql.NullTime
}
